TABLES_MAP = {   'assigned_client': {   'fields': {   'assigned_client_id': {   'datatype': 'UUID',
                                                                   'is_nullable': False,
                                                                   'is_pk': True,
                                                                   'is_unique': True},
                                         'client_id': {   'datatype': 'UUID',
                                                          'fk': {   'on_delete': 'cascade',
                                                                    'on_update': 'no '
                                                                                 'action',
                                                                    'to': 'client'},
                                                          'is_nullable': False,
                                                          'is_pk': False,
                                                          'is_unique': False},
                                         'created_at': {   'auto_update': 'save',
                                                           'datatype': 'datetime',
                                                           'is_date': True,
                                                           'is_nullable': False,
                                                           'is_pk': False,
                                                           'is_unique': False},
                                         'subscription_id': {   'datatype': 'UUID',
                                                                'fk': {   'on_delete': 'cascade',
                                                                          'on_update': 'no '
                                                                                       'action',
                                                                          'to': 'subscription'},
                                                                'is_nullable': False,
                                                                'is_pk': False,
                                                                'is_unique': False}}},
    'backup': {   'backup': {   'fields': {   'backup_id': {   'datatype': 'UUID',
                                                               'is_nullable': False,
                                                               'is_pk': True,
                                                               'is_unique': True},
                                              'timestamp': {   'auto_update': 'save',
                                                               'datatype': 'datetime',
                                                               'is_date': True,
                                                               'is_nullable': False,
                                                               'is_pk': False,
                                                               'is_unique': False}}}},
    'client': {   'fields': {   'client_id': {   'datatype': 'UUID',
                                                 'is_nullable': False,
                                                 'is_pk': True,
                                                 'is_unique': True},
                                'company_name': {   'datatype': 'str',
                                                    'is_nullable': True,
                                                    'is_pk': False,
                                                    'is_unique': False},
                                'created_at': {   'auto_update': 'save',
                                                  'datatype': 'datetime',
                                                  'is_date': True,
                                                  'is_nullable': False,
                                                  'is_pk': False,
                                                  'is_unique': False},
                                'display_name': {   'datatype': 'str',
                                                    'is_nullable': False,
                                                    'is_pk': False,
                                                    'is_unique': False},
                                'email': {   'datatype': 'str',
                                             'is_nullable': True,
                                             'is_pk': False,
                                             'is_unique': False},
                                'first_name': {   'datatype': 'str',
                                                  'is_nullable': True,
                                                  'is_pk': False,
                                                  'is_unique': False},
                                'last_name': {   'datatype': 'str',
                                                 'is_nullable': True,
                                                 'is_pk': False,
                                                 'is_unique': False},
                                'phone': {   'datatype': 'str',
                                             'is_nullable': False,
                                             'is_pk': False,
                                             'is_unique': True},
                                'updated_at': {   'auto_update': 'update',
                                                  'datatype': 'datetime',
                                                  'is_date': True,
                                                  'is_nullable': False,
                                                  'is_pk': False,
                                                  'is_unique': False}}},
    'payment': {   'fields': {   'amount': {   'datatype': 'int',
                                               'is_nullable': False,
                                               'is_pk': False,
                                               'is_unique': False},
                                 'client_id': {   'datatype': 'UUID',
                                                  'fk': {   'on_delete': 'cascade',
                                                            'on_update': 'no '
                                                                         'action',
                                                            'to': 'client'},
                                                  'is_nullable': False,
                                                  'is_pk': False,
                                                  'is_unique': False},
                                 'created_at': {   'auto_update': 'save',
                                                   'datatype': 'datetime',
                                                   'is_date': True,
                                                   'is_nullable': False,
                                                   'is_pk': False,
                                                   'is_unique': False},
                                 'payment_id': {   'datatype': 'UUID',
                                                   'is_nullable': False,
                                                   'is_pk': True,
                                                   'is_unique': True},
                                 'subscription_id': {   'datatype': 'UUID',
                                                        'fk': {   'on_delete': 'cascade',
                                                                  'on_update': 'no '
                                                                               'action',
                                                                  'to': 'subscription'},
                                                        'is_nullable': False,
                                                        'is_pk': False,
                                                        'is_unique': False},
                                 'updated_at': {   'auto_update': 'update',
                                                   'datatype': 'datetime',
                                                   'is_date': True,
                                                   'is_nullable': False,
                                                   'is_pk': False,
                                                   'is_unique': False}}},
    'plan': {   'fields': {   'created_at': {   'auto_update': 'save',
                                                'datatype': 'datetime',
                                                'is_date': True,
                                                'is_nullable': False,
                                                'is_pk': False,
                                                'is_unique': False},
                              'duration': {   'datatype': 'int',
                                              'is_nullable': False,
                                              'is_pk': False,
                                              'is_unique': False},
                              'guest_pass': {   'datatype': 'int',
                                                'is_nullable': False,
                                                'is_pk': False,
                                                'is_unique': False},
                              'plan_id': {   'datatype': 'UUID',
                                             'is_nullable': False,
                                             'is_pk': True,
                                             'is_unique': True},
                              'plan_name': {   'datatype': 'str',
                                               'is_nullable': False,
                                               'is_pk': False,
                                               'is_unique': True},
                              'plan_type': {   'datatype': 'str',
                                               'is_nullable': False,
                                               'is_pk': False,
                                               'is_unique': False},
                              'price': {   'datatype': 'int',
                                           'is_nullable': False,
                                           'is_pk': False,
                                           'is_unique': False},
                              'slot': {   'datatype': 'int',
                                          'is_nullable': False,
                                          'is_pk': False,
                                          'is_unique': False},
                              'updated_at': {   'auto_update': 'update',
                                                'datatype': 'datetime',
                                                'is_date': True,
                                                'is_nullable': False,
                                                'is_pk': False,
                                                'is_unique': False}}},
    'subscription': {   'fields': {   'client_id': {   'datatype': 'str',
                                                       'fk': {   'on_delete': 'cascade',
                                                                 'on_update': 'no '
                                                                              'action',
                                                                 'to': 'client'},
                                                       'is_nullable': False,
                                                       'is_pk': False,
                                                       'is_unique': False},
                                      'created_at': {   'auto_update': 'save',
                                                        'datatype': 'datetime',
                                                        'is_date': True,
                                                        'is_nullable': False,
                                                        'is_pk': False,
                                                        'is_unique': False},
                                      'discount': {   'datatype': 'int',
                                                      'is_nullable': False,
                                                      'is_pk': False,
                                                      'is_unique': False},
                                      'discount_type': {   'datatype': 'str',
                                                           'is_nullable': False,
                                                           'is_pk': False,
                                                           'is_unique': False},
                                      'expiration_date': {   'datatype': 'str',
                                                             'is_nullable': False,
                                                             'is_pk': False,
                                                             'is_unique': False},
                                      'payment_status': {   'datatype': 'str',
                                                            'is_nullable': False,
                                                            'is_pk': False,
                                                            'is_unique': False},
                                      'plan_id': {   'datatype': 'str',
                                                     'fk': {   'on_delete': 'cascade',
                                                               'on_update': 'no '
                                                                            'action',
                                                               'to': 'plan'},
                                                     'is_nullable': False,
                                                     'is_pk': False,
                                                     'is_unique': False},
                                      'plan_unit': {   'datatype': 'int',
                                                       'is_nullable': False,
                                                       'is_pk': False,
                                                       'is_unique': False},
                                      'status': {   'datatype': 'str',
                                                    'is_nullable': False,
                                                    'is_pk': False,
                                                    'is_unique': False},
                                      'subscription_id': {   'datatype': 'str',
                                                             'is_nullable': False,
                                                             'is_pk': True,
                                                             'is_unique': True},
                                      'updated_at': {   'auto_update': 'update',
                                                        'datatype': 'str',
                                                        'is_date': True,
                                                        'is_nullable': False,
                                                        'is_pk': False,
                                                        'is_unique': False},
                                      'vat': {   'datatype': 'int',
                                                 'is_nullable': False,
                                                 'is_pk': False,
                                                 'is_unique': False}}},
    'visit': {   'fields': {   'client_id': {   'datatype': 'UUID',
                                                'fk': {   'on_delete': 'cascade',
                                                          'on_update': 'no '
                                                                       'action',
                                                          'to': 'client'},
                                                'is_nullable': False,
                                                'is_pk': False,
                                                'is_unique': False},
                               'subscription_id': {   'datatype': 'UUID',
                                                      'fk': {   'on_delete': 'cascade',
                                                                'on_update': 'no '
                                                                             'action',
                                                                'to': 'subscription'},
                                                      'is_nullable': False,
                                                      'is_pk': False,
                                                      'is_unique': False},
                               'timestamp': {   'auto_update': 'save',
                                                'datatype': 'datetime',
                                                'is_date': True,
                                                'is_nullable': False,
                                                'is_pk': False,
                                                'is_unique': False},
                               'visit_id': {   'datatype': 'UUID',
                                               'is_nullable': False,
                                               'is_pk': True,
                                               'is_unique': True}}}}